# Generated by Django 4.2 on 2023-04-23 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_article_posted_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 23, 16, 35, 27, 608864), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 23, 16, 35, 27, 609864), verbose_name='Дата'),
        ),
    ]
