# Generated by Django 4.2 on 2023-04-23 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_article_posted_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 23, 17, 51, 41, 148443), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 23, 17, 51, 41, 148443), verbose_name='Дата'),
        ),
    ]
